### ISSUE TITLE
FrameRateController cannot be Instantiated from code

### ISSUE THREAD

**Issue by LukeAvery92** [dubit/duck#73]
The frame rate controller prefab sits within the scripts folder of Utils. It would be ideal for programmers to be able to create this from a resources folder.

**Comment by Rollo-Liu** [comment]
Ez. I shall get it done.

**Comment by kkjamie** [comment]
This was discussed before. If you add it to resources it's included in your build, whether you use it or not. Even if you are using it there is no easy way to omit it from your build for production. It's easy enough to drag it in there and have it in your project.

**Comment by danhalldubit** [comment]
Usually you'll want to move the counter to the corner that's least in the way of your game / UI anyway
