### ISSUE TITLE
Key Value Pair Data Structure Extenstion  - GetOrCreate

### ISSUE THREAD

**Issue by LukeAvery92** [dubit/duck#78]
Often we have to write the following:

```
Dictionary<SomeKey, SomeValue> keyValuePairStructure = new Dictionary<SomeKey, SomeValue>();

if (!keyValuePairStructure.ContainsKey(someKey))
{
	keyValuePairStructure.Add(someKey, new DefaultValue());
}

keyValuePairStructure[someKey].Add(someValue);
```

Would be nice if we had an extenstion function that removed this need.

```
T2 GetOrCreateValue(T1 key, T2 value)

var value = keyValuePairStructure.GetOrCreate(TKey key, TValue defaultValue)
```

**Comment by HarryHodgson** [comment]
They already have this functionality.

It's
```
keyValuePairStructure[someKey] = someValue
```

And if its doesn't exist it will add it, if it does exist it will assign it.

**Comment by LukeAvery92** [comment]
It was for instances like this:

```
Dictionary<SomeKey, List<SomeValue>> keyValuePairStructure = new Dictionary<SomeKey, List<SomeValue>>();

if (!keyValuePairStructure.ContainsKey(someKey))
{
	keyValuePairStructure.Add(someKey, new List<SomeValue>());
}

keyValuePairStructure[someKey].Add(someValue);
```

**Comment by HarryHodgson** [comment]
Ah thats specific to lists then, not just `SomeValue`.

Yeah, I can see it being handy.

**Comment by HarryHodgson** [comment]
My line will do AssignOrCreate just fine, what the suggested Util does extra is to initlaize a list to then `Add` the value to the list. I think its slightly different, if you wanted something other than a list it requires more util methods. Im not sure how this is `GetOrCreate`.

**Comment by kkjamie** [comment]
I think there is just a misunderstanding

Yours is`AssignOrCreate`. The suggestion here is `GetOrCreate`.

it's this:
```
public static void GetOrCreate<K,V>(this Dictionary<K,V> dictionary, K key, V defaultValue)
{
    if (!dictionary.ContainsKey(key))
    {
        dictionary[key] = defaultValue;
    }
    return dictionary[key];
}
```

Usage
```
var harryList = dictionary.GetOrCreate("harry", new List<object>());
```

If theres already a list registered under harry I just get it. If not it inserts the defaultValue....

More explicitly it's actually `get-and-return-or-create-and-set-on-the-dictionary-and-return`

Side note: this implementation is a bit naff since you always new a list. I'd prefer to pass a `Func<Value>` and only call that if we need to create the default value

**Comment by Rollo-Liu** [comment]
OMG TOO MUCH GC OVERHEAD

**Comment by LukeAvery92** [comment]
Good spot @Rollo-Liu

**Comment by kkjamie** [comment]
I think closing was a bit premature

I think Chuan was half joking. Yes the example I showed was not efficient at all as I mentioned in the last line of my comment. Every time you use the function you have to pass a default value, which in this case is a `new List<object>()` every single time. The `Func<T>` option could work: `dictionary.GetOrCreate("harry", () => new List<object>());` Although again we create some garbage (a new anonymous function every usage. Possibly we could force T to be newable with an empty constructor. and then new it inside the function. This would be less flexible however but probably satisfies the most common use cases.

Also I'd just like to mention on GC... In most of our projects we all make plenty of garbage. It's not optimal but guess what? This is not C++. We have this thing the garbage collector. I'm not advocating being fast and loose. I'd prefer that everybody keep your allocations in check, and not overwork the garbage collector. During in initialization it's not uncommon to allocate stuff, to do you calculations and get to the data you need. That's the primary use case of this util. Normally I write the code inside this function when I'm populating a series of lists or collecting data from somewhere else. That's a one time allocation, Eventually if we hit our allocations grow the GC will come get it, but I know it's not gonna build again during the game or level. It's perfectly acceptable to me to allocate during these times. The alternative is overly optimized code that is likely to be unreadable, with data structures that just don't make sense.

With that in mind I'd prefer to go for the `new ()` version which is GC free with an overload that takes a `Func<T>`. The GC on second option depends on usage, if you use an anonymous function in each usage of course theres a bit of GC there. If you use a member function or cache the anonymous function then you are minimal or even free depending on situation.

**Comment by pmead** [comment]
To me this looks a lot like you're trying to use a factory or builder pattern around a register of objects.
I'm not sure how important a use case this is, but here's my 2 cents anyway.

Not sure how I feel about extending dictionary to do this and not having a factory / builder function ecosystem. But if you were to continue down this path I'd suggest a little inversion of control around the invocation of the factory or constructor, that way you can make sure the factory isn't being run unnecessarily quite easily.

e.g.

```
public static V GetOrCreate<K, V>(this Dictionary<K, V> dictionary, K key) where V : new()
{
	if (!dictionary.ContainsKey(key))
	{
		dictionary[key] = new V();
	}

	return dictionary[key];
}
```

You can then use overloads if you want to push some control over what is constructed back to the end user. For example you could allow a default value (see jamie's comment above) or allow factory functions to be passed in.

e.g.

```
// This implementation isn't as safe as it could be it can throw at run-time 
// e.g. If the argument length miss matches the delegate or the delegate doesn't return V
// Func<T1,T2,...TN,Result> would be safer but this is a quickly made example
public static V GetOrCreate<K, V>(this Dictionary<K, V> dictionary, K key, Delegate factory, params object[] args)
{
	if (!dictionary.ContainsKey(key))
	{
		dictionary[key] = (V)factory.DynamicInvoke(args);
	}

	return dictionary[key];
}

```
-----
On another note, I just wanted to point out @kkjamie and @HarryHodgson you do mean different things and I think you're still conflating them with the vernacular.
The real difference here is not assign or create but **get** and assign if and only if that fails and **replace**/assign always without prejudice.

Both paradigms can accommodate assignation and creation, by swapping constructors and pre-constructed values or value types, thus trying to establish the difference using those terms looked like it caused the most confusion.

**Comment by pmead** [comment]
It is basically an expansion on your _side note_ (now that I've spotted it)
> sidenote:  I'd prefer to pass a Func<Value> and only call that if we need to create the default value

Which really ought not to have been a side note, commit man! Its more compelling than the stuff you wrote above it. My addition is really just that you can overload this to suite other needs, such as being able to simply instantiate the type without writing anonymous functions everywhere.

On Func vs args, this wasn't meant to be an important part hence my comment above the code recognising that Func<T...> might be better. If the convention is to prefer curried functions over passing args into your factory then I'm more than happy with that.

**Comment by kkjamie** [comment]
Fair enough.
